on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: blog   
  AZURE_WEBAPP_PACKAGE_PATH: '.' 
  NODE_VERSION: '20'      

permissions:
  contents: write  # 需要写权限以推送到 gh-deploy 分支

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies and build
      run: |
        npm install
        npm run docs:build 
    - name: Debug directory
      run: |
        echo "Checking build output directory..."
        ls -al .vitepress
        ls -al .vitepress/dist
    - name: Deploy to gh-deploy branch
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git checkout --orphan gh-deploy
        git --work-tree=.vitepress/dist add --all
        git --work-tree=.vitepress/dist commit -m "Deploy to gh-deploy branch"
        git push origin HEAD:gh-deploy --force